# GoPro Configuration for Framingo Example
# Format: github.com/xhanio/gopro/pkg/types/config.go

product: framingo-example
version: v1.0.0

default:
  binary_src: build/binary
  binary_tgt: bin/
  binary_build_env:
    - CGO_ENABLED=1
  binary_build_args:
    - -v
    - -gcflags
    - '-N -l'
  image_build_src: build/image
  image_prefix: localhost:5000
  config_src: env/default/config
  config_tgt: dist/default/config
  kubernetes_src: env/default/kubernetes
  kubernetes_tgt: dist/default/kubernetes

  binaries:
    - exampleapp
    - examplecli
  images:
    - postgres
    - exampleapp
  configs:
    - exampleapp
  kubernetes_templates:
    - exampleapp
    - postgres

env:
  local:
    binary_build_env:
      - CGO_ENABLED=1

    config_src: env/local/config
    config_tgt: dist/local/config

    docker_compose_src: env/local/docker-compose
    docker_compose_tgt: dist/local

build:
  binaries:
    - name: exampleapp
      config_dir: dist/local/config/exampleapp
    - name: examplecli

  images:
    - name: postgres
      build_from: postgres:16-alpine
    - name: exampleapp
      base: ubuntu:22.04

generate:
  configs:
    - name: exampleapp
      files:
        - config.yaml
        - migrations/*.sql

  docker_compose:
    files:
      - docker-compose.yaml
